# Generated by Django 6.0.2 on 2026-03-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
