# Generated by Django 6.0.2 on 2026-03-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
