# Generated by Django 6.0.2 on 2026-03-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_public',
            new_name='titles_is_public',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist_is_public',
            field=models.BooleanField(default=False),
        ),
    ]
