# Generated by Django 6.0.2 on 2026-04-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_king',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
