# Generated by Django 6.0.2 on 2026-03-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('year_start', models.PositiveIntegerField(max_length=5)),
                ('category', models.CharField(choices=[('MV', 'Movie'), ('SR', 'Series'), ('ANM', 'Anime'), ('CRT', 'Cartoon'), ('LG', 'Legal case'), ('VD', 'Youtube video ot other'), ('READ', 'Written content')], default='SR', max_length=7)),
                ('year_end', models.PositiveIntegerField(max_length=5, null=True)),
                ('director', models.CharField(blank=True, max_length=150, null=True)),
                ('synopsis', models.TextField(blank=True, max_length=600, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, help_text='run time in minutes for movie', max_length=6, null=True)),
                ('episodes', models.PositiveIntegerField(blank=True, help_text='number of episodes', max_length=6, null=True)),
                ('seasons', models.PositiveIntegerField(blank=True, help_text='number of seasons', max_length=6, null=True)),
            ],
        ),
    ]
