# Generated by Django 6.0.2 on 2026-03-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='episodes',
            field=models.PositiveIntegerField(blank=True, help_text='number of episodes', null=True),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='runtime',
            field=models.PositiveIntegerField(blank=True, help_text='run time in minutes for movie', null=True),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='seasons',
            field=models.PositiveIntegerField(blank=True, help_text='number of seasons', null=True),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='year_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='year_start',
            field=models.PositiveIntegerField(),
        ),
    ]
