# Generated by Django 6.0.2 on 2026-03-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_alter_watchlistitem_episodes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='episodes',
            field=models.PositiveIntegerField(blank=True, help_text='number of episodes for series', null=True),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='seasons',
            field=models.PositiveIntegerField(blank=True, help_text='number of seasons for series', null=True),
        ),
    ]
