# Generated by Django 6.0.2 on 2026-03-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_watchlistitem_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='synopsis',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
