# Generated by Django 6.0.2 on 2026-04-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_alter_watchlistitem_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
