# Generated by Django 6.0.2 on 2026-02-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('year', models.PositiveIntegerField()),
                ('director', models.CharField(max_length=200)),
                ('review', models.TextField()),
                ('cover', models.URLField()),
                ('start_watch', models.DateField()),
                ('end_watch', models.CharField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
