# Generated by Django 6.0.2 on 2026-02-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='end_watch',
            field=models.DateField(),
        ),
    ]
