# Generated by Django 6.0.2 on 2026-02-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_alter_title_end_watch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='year',
            new_name='year_start',
        ),
        migrations.AddField(
            model_name='title',
            name='year_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
