# Generated by Django 6.0.2 on 2026-03-01 07:48

import titles.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_rename_year_title_year_start_title_year_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='category',
            field=models.CharField(choices=[('MV', 'Movie'), ('SR', 'Series'), ('ANM', 'Anime'), ('CRT', 'Cartoon'), ('LG', 'Legal case'), ('VD', 'Youtube video ot other'), ('RD', 'Written content')], default='SR', max_length=5),
        ),
        migrations.AddField(
            model_name='title',
            name='status',
            field=models.CharField(choices=[('DONE', 'Done or ended'), ('DROP', 'Dropped'), ('RVS', 'Revisit or Finish'), ('WATCH', 'Watching')], default='DONE', max_length=5),
        ),
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10), titles.models.rating_validator]),
        ),
    ]
