# Generated by Django 6.0.2 on 2026-03-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_title_category_title_status_alter_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.CharField(choices=[('MV', 'Movie'), ('SR', 'Series'), ('ANM', 'Anime'), ('CRT', 'Cartoon'), ('LG', 'Legal case'), ('VD', 'Youtube video ot other'), ('READ', 'Written content')], default='SR', max_length=7),
        ),
        migrations.AlterField(
            model_name='title',
            name='status',
            field=models.CharField(choices=[('DONE', 'Done'), ('DROP', 'Dropped'), ('RVS', 'Revisit or Finish'), ('WATCH', 'Watching')], default='DONE', max_length=5),
        ),
    ]
