# Generated by Django 6.0.2 on 2026-03-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_alter_title_category_alter_title_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='end_watch',
            field=models.DateField(blank=True, null=True),
        ),
    ]
