# Generated by Django 6.0.2 on 2026-03-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_title_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
