# Generated by Django 6.0.2 on 2026-03-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0008_alter_title_cover_alter_title_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.CharField(choices=[('MV', 'Movie'), ('SR', 'Series'), ('ANM', 'Anime'), ('CRT', 'Cartoon'), ('LG', 'Legal case'), ('VD', 'Youtube video ot other'), ('READ', 'Written content'), ('OTHER', 'Other')], default='MV', max_length=7),
        ),
    ]
