# Generated by Django 6.0.2 on 2026-03-28 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0009_alter_title_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='start_watch',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
