# Generated by Django 6.0.2 on 2026-03-28 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0010_alter_title_start_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='end_watch',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='title',
            name='start_watch',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
