# Generated by Django 6.0.2 on 2026-03-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0011_alter_title_end_watch_alter_title_start_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='review',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='start_watch',
            field=models.DateField(blank=True, null=True),
        ),
    ]
