# Generated by Django 6.0.2 on 2026-03-31 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0012_alter_title_review_alter_title_start_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='end_watch',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
