# Generated by Django 6.0.2 on 2026-04-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0013_alter_title_end_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='year_start',
            field=models.IntegerField(),
        ),
    ]
